stages:
  - deploy
  - test

deploy:
  stage: deploy
  image: python:3.11-slim
  script:
    - echo "Installing Microblog dependencies"
    - pip install -r ./microblog/requirements.txt
    - echo "Deploying to local server"
    - cd ./microblog
    - ./boot.sh &
    - sleep 5

unit-test:
  stage: test
  image: python:3.11-slim
  script:
    - echo "Installing Microblog dependencies"
    - pip install -r ./microblog/requirements.txt
    - echo "Running unit-tests"
    - cd ./microblog/
    - python -m tests

crawler-test:
  stage: test
  image: python:3.11-slim
  variables: 
    FF_NETWORK_PER_BUILD: 1
  services: 
    - selenium/standalone-chrome
  script:
    - echo "Installing Crawler dependencies"
    - pip install -r ./crawler/requirements.txt
    - echo "Running Crawler"
    - python -m crawler.crawler --headless
